import {
  InvoiceData,
  NavMenuData,
  RecipientData,
  TransactionData,
  UserData,
} from "./types";

export const topNavMenuDataList: NavMenuData[] = [
  {
    name: "Dashboard",
    addresses: [""],
    subNavMenu: [],
    iconName: "dashboard",
  },
  {
    name: "Invoices",
    addresses: ["/invoices"],
    subNavMenu: [],
    iconName: "invoices",
  },
  {
    name: "Messages",
    addresses: [""],
    subNavMenu: [],
    iconName: "messages",
  },
  {
    name: "My Wallets",
    addresses: [""],
    subNavMenu: [],
    iconName: "my-wallets",
  },
  {
    name: "Activity",
    addresses: ["/recipients", "/transactions"],
    subNavMenu: [
      {
        name: "Recipients",
        address: "/recipients",
      },
      { name: "Transactions", address: "/transactions" },
    ],
    iconName: "activity",
  },
  {
    name: "Analytics",
    addresses: [""],
    subNavMenu: [],
    iconName: "analytics",
  },
];

export const bottomNavMenuDataList: NavMenuData[] = [
  {
    name: "Get Help",
    addresses: [""],
    subNavMenu: [],
    iconName: "get-help",
  },
  {
    name: "Settings",
    addresses: [""],
    subNavMenu: [],
    iconName: "settings",
  },
];

export const transactionDataList: TransactionData[] = [
  {
    id: 0,
    name: "Stripe",
    imageName: "stripe",
    business: "Witdraw",
    date: "Jan 29,2022",
    time: "at 8.00 PM",
    invoiceId: "PMX09812",
    amount: +300.0,
    currency: "USD",
    status: "Pending",
    actions: "Details",
  },

  {
    id: 1,
    name: "Bitcoin transaction",
    imageName: "bitcoin",
    business: "Deposit",
    date: "Jan 25,2022",
    time: "at 9.15 AM",
    invoiceId: "PMX0979",
    amount: -890.15,
    currency: "USD",
    status: "Success",
    actions: "Details",
  },

  {
    id: 2,
    name: "Facebook charge",
    imageName: "facebook",
    business: "Advertising",
    date: "Jan 25,2022",
    time: "at 6.45 AM",
    invoiceId: "OVF19244",
    amount: -600.0,
    currency: "USD",
    status: "Success",
    actions: "Details",
  },

  {
    id: 3,
    name: "Upwork",
    imageName: "upwork",
    business: "Business",
    date: "Jan 23,2022",
    time: "at 9.00 PM",
    invoiceId: "AMX09871",
    amount: +1243.0,
    currency: "USD",
    status: "Pending",
    actions: "Details",
  },

  {
    id: 4,
    name: "Send to Antonio",
    imageName: "antonio",
    business: "Transfer",
    date: "Jan 15,2022",
    time: "at 10.15 AM",
    invoiceId: "PMX09873",
    amount: -123.0,
    currency: "USD",
    status: "Failed",
    actions: "Details",
  },

  {
    id: 5,
    name: "UI8.net",
    imageName: "UI8",
    business: "Payment",
    date: "Jan 15,2022",
    time: "at 09.00 AM",
    invoiceId: "AMX89786",
    amount: -190.0,
    currency: "USD",
    status: "Success",
    actions: "Details",
  },
  {
    id: 6,
    name: "Bank of America",
    imageName: "bank",
    business: "Witdraw",
    date: "Jan 15,2022",
    time: "at 07.00 AM",
    invoiceId: "AMX89785",
    amount: -1565.99,
    currency: "USD",
    status: "Success",
    actions: "Details",
  },

  {
    id: 7,
    name: "UI8.net",
    imageName: "UI8",
    business: "Payment",
    date: "Jan 11,2022",
    time: "at 09.00 PM",
    invoiceId: "AMX76543",
    amount: -10.0,
    currency: "USD",
    status: "Success",
    actions: "Details",
  },
];

export const RecipientDataList: RecipientData[] = [
  {
    name: "Guy Hawkins",
    imageName: "guy",
    email: "guy.hawkins@mail.com",
    accountType: "Business",
    currency: "USD",
    date: "20 Jan 2022, 09.00 PM",
  },
  {
    name: "Roselle Ehrman",
    imageName: "roselle",
    email: "roselleehrman@mail.com",
    accountType: "Personal",
    currency: "GBP",
    date: "20 Jan 2022, 07.00 PM",
  },
  {
    name: "Marielle Wiging",
    imageName: "marielle",
    email: "wiging_marie@mail.com",
    accountType: "Personal",
    currency: "EUR",
    date: "20 Jan 2022, 06.00 PM",
  },
  {
    name: "Cyndy Lillibridge",
    imageName: "cyndy",
    email: "cindylilibridge@mail.com",
    accountType: "Business",
    currency: "EUR",
    date: "17 Jan 2022, 10.00 PM",
  },
  {
    name: "Darcel Ballentine",
    imageName: "darcel",
    email: "darcelballenti@mail.com",
    accountType: "Personal",
    currency: "EUR",
    date: "15 Jan 2022, 04.00 PM",
  },
  {
    name: "Tanner Stafford",
    imageName: "tanner",
    email: "stafford.tenn@mail.com",
    accountType: "Business",
    currency: "GBP",
    date: "15 Jan 2022, 09.00 PM",
  },
  {
    name: "Francene Vandyne",
    imageName: "francene",
    email: "vandyne0090@mail.com",
    accountType: "Business",
    currency: "USD",
    date: "13 Jan 2022, 08.00 PM",
  },
  {
    name: "Elmer Laverty",
    imageName: "elmer",
    email: "guy.hawkins@mail.com",
    accountType: "Personal",
    currency: "GBP",
    date: "12 Jan 2022, 11.00 PM",
  },
];

export const UserInfoData: UserData = {
  userName: "Alesia K.",
  imageName: "alesia",
};
export const InvoiceDataList: InvoiceData[] = [
  {
    name: "New Design Project",
    invoiceId: "INV110XXX",
    date: "January 05, 2022",
    client: "Biffco Enterprises",
    price: 1240.0,
    currency: "USD",
    status: "Unpaid",
  },
  {
    name: "Crypto Project",
    invoiceId: "INV109XXX",
    date: "January 02, 2022",
    client: "Acme Co.",
    price: 4367.67,
    currency: "USD",
    status: "Unpaid",
  },
  {
    name: "Sarimun Design",
    invoiceId: "INV108XXX",
    date: "January 01, 2022",
    client: "Big Kahuna Burger",
    price: 980.0,
    currency: "USD",
    status: "Pending",
  },
  {
    name: "Abstergo Development",
    invoiceId: "INV107XXX",
    date: "January 01, 2022",
    client: "Abstergo Ltd.",
    price: 5789.0,
    currency: "USD",
    status: "Refund",
  },
  {
    name: "Barone Website",
    invoiceId: "INV106XXX",
    date: "December 29, 2021",
    client: "Barone LLC.",
    price: 3567.0,
    currency: "USD",
    status: "Success",
  },
  {
    name: "Barone Website",
    invoiceId: "INV106XXX",
    date: "December 29, 2021",
    client: "Barone LLC.",
    price: 3567.0,
    currency: "USD",
    status: "Paid",
  },
  {
    name: "Biffco Mobile App",
    invoiceId: "INV105XXX",
    date: "December 25, 2021",
    client: "Biffco Enterprises",
    price: 6345.23,
    currency: "USD",
    status: "Paid",
  },
];
